/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicPlisioWebhookRouteImport } from './routes/api/public/plisio-webhook'
import { Route as ApiPublicPlisioCreateInvoiceRouteImport } from './routes/api/public/plisio-create-invoice'
import { Route as ApiPublicHooksPlisioRetryQueueRouteImport } from './routes/api/public/hooks/plisio-retry-queue'
import { Route as ApiPublicHooksDomainHealthRouteImport } from './routes/api/public/hooks/domain-health'
import { Route as ApiPublicHooksBackfillClicksRouteImport } from './routes/api/public/hooks/backfill-clicks'
import { Route as ApiPublicHooksAutopilotRouteImport } from './routes/api/public/hooks/autopilot'

const ApiPublicPlisioWebhookRoute = ApiPublicPlisioWebhookRouteImport.update({
  id: '/api/public/plisio-webhook',
  path: '/api/public/plisio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlisioCreateInvoiceRoute =
  ApiPublicPlisioCreateInvoiceRouteImport.update({
    id: '/api/public/plisio-create-invoice',
    path: '/api/public/plisio-create-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPlisioRetryQueueRoute =
  ApiPublicHooksPlisioRetryQueueRouteImport.update({
    id: '/api/public/hooks/plisio-retry-queue',
    path: '/api/public/hooks/plisio-retry-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDomainHealthRoute =
  ApiPublicHooksDomainHealthRouteImport.update({
    id: '/api/public/hooks/domain-health',
    path: '/api/public/hooks/domain-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillClicksRoute =
  ApiPublicHooksBackfillClicksRouteImport.update({
    id: '/api/public/hooks/backfill-clicks',
    path: '/api/public/hooks/backfill-clicks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutopilotRoute = ApiPublicHooksAutopilotRouteImport.update({
  id: '/api/public/hooks/autopilot',
  path: '/api/public/hooks/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/public/plisio-create-invoice': typeof ApiPublicPlisioCreateInvoiceRoute
  '/api/public/plisio-webhook': typeof ApiPublicPlisioWebhookRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/backfill-clicks': typeof ApiPublicHooksBackfillClicksRoute
  '/api/public/hooks/domain-health': typeof ApiPublicHooksDomainHealthRoute
  '/api/public/hooks/plisio-retry-queue': typeof ApiPublicHooksPlisioRetryQueueRoute
}
export interface FileRoutesByTo {
  '/api/public/plisio-create-invoice': typeof ApiPublicPlisioCreateInvoiceRoute
  '/api/public/plisio-webhook': typeof ApiPublicPlisioWebhookRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/backfill-clicks': typeof ApiPublicHooksBackfillClicksRoute
  '/api/public/hooks/domain-health': typeof ApiPublicHooksDomainHealthRoute
  '/api/public/hooks/plisio-retry-queue': typeof ApiPublicHooksPlisioRetryQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public/plisio-create-invoice': typeof ApiPublicPlisioCreateInvoiceRoute
  '/api/public/plisio-webhook': typeof ApiPublicPlisioWebhookRoute
  '/api/public/hooks/autopilot': typeof ApiPublicHooksAutopilotRoute
  '/api/public/hooks/backfill-clicks': typeof ApiPublicHooksBackfillClicksRoute
  '/api/public/hooks/domain-health': typeof ApiPublicHooksDomainHealthRoute
  '/api/public/hooks/plisio-retry-queue': typeof ApiPublicHooksPlisioRetryQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/public/plisio-create-invoice'
    | '/api/public/plisio-webhook'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/backfill-clicks'
    | '/api/public/hooks/domain-health'
    | '/api/public/hooks/plisio-retry-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/public/plisio-create-invoice'
    | '/api/public/plisio-webhook'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/backfill-clicks'
    | '/api/public/hooks/domain-health'
    | '/api/public/hooks/plisio-retry-queue'
  id:
    | '__root__'
    | '/api/public/plisio-create-invoice'
    | '/api/public/plisio-webhook'
    | '/api/public/hooks/autopilot'
    | '/api/public/hooks/backfill-clicks'
    | '/api/public/hooks/domain-health'
    | '/api/public/hooks/plisio-retry-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicPlisioCreateInvoiceRoute: typeof ApiPublicPlisioCreateInvoiceRoute
  ApiPublicPlisioWebhookRoute: typeof ApiPublicPlisioWebhookRoute
  ApiPublicHooksAutopilotRoute: typeof ApiPublicHooksAutopilotRoute
  ApiPublicHooksBackfillClicksRoute: typeof ApiPublicHooksBackfillClicksRoute
  ApiPublicHooksDomainHealthRoute: typeof ApiPublicHooksDomainHealthRoute
  ApiPublicHooksPlisioRetryQueueRoute: typeof ApiPublicHooksPlisioRetryQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public/plisio-webhook': {
      id: '/api/public/plisio-webhook'
      path: '/api/public/plisio-webhook'
      fullPath: '/api/public/plisio-webhook'
      preLoaderRoute: typeof ApiPublicPlisioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plisio-create-invoice': {
      id: '/api/public/plisio-create-invoice'
      path: '/api/public/plisio-create-invoice'
      fullPath: '/api/public/plisio-create-invoice'
      preLoaderRoute: typeof ApiPublicPlisioCreateInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/plisio-retry-queue': {
      id: '/api/public/hooks/plisio-retry-queue'
      path: '/api/public/hooks/plisio-retry-queue'
      fullPath: '/api/public/hooks/plisio-retry-queue'
      preLoaderRoute: typeof ApiPublicHooksPlisioRetryQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/domain-health': {
      id: '/api/public/hooks/domain-health'
      path: '/api/public/hooks/domain-health'
      fullPath: '/api/public/hooks/domain-health'
      preLoaderRoute: typeof ApiPublicHooksDomainHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-clicks': {
      id: '/api/public/hooks/backfill-clicks'
      path: '/api/public/hooks/backfill-clicks'
      fullPath: '/api/public/hooks/backfill-clicks'
      preLoaderRoute: typeof ApiPublicHooksBackfillClicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autopilot': {
      id: '/api/public/hooks/autopilot'
      path: '/api/public/hooks/autopilot'
      fullPath: '/api/public/hooks/autopilot'
      preLoaderRoute: typeof ApiPublicHooksAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiPublicPlisioCreateInvoiceRoute: ApiPublicPlisioCreateInvoiceRoute,
  ApiPublicPlisioWebhookRoute: ApiPublicPlisioWebhookRoute,
  ApiPublicHooksAutopilotRoute: ApiPublicHooksAutopilotRoute,
  ApiPublicHooksBackfillClicksRoute: ApiPublicHooksBackfillClicksRoute,
  ApiPublicHooksDomainHealthRoute: ApiPublicHooksDomainHealthRoute,
  ApiPublicHooksPlisioRetryQueueRoute: ApiPublicHooksPlisioRetryQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
